---
name: "📕 Documentation Issue"
description: Report an issue in the rule documentation or Developer Guide
title: "(short issue description)"
labels: [documentation]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: A clear and concise description of the issue.
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: Links
      description: |
        Provide links to any documents that you think need correction or modification.
    validations:
      required: false
